import AuditorIndustry from "../../models/auditor/auditorIndustry.js";

const auditorIndustries = [
  "Accounting",
  "Agriculture and Non-petrol Natural Resource Extraction",
  "Broadcasting Printing and Publishing",
  "Brokers",
  "Building Supply Retail",
  "Business Services",
  "Consumer Services",
  "Design, Direction and Creative Management",
  "Distributors, Dispatchers and Processors",
  "Doctor's Offices and Clinics",
  "Durable Manufacturing",
  "Eating and Drinking Places",
  "Entertainment Retail",
  "Equipment Rental and Leasing",
  "Financial",
  "Food and Tobacco Processing",
  "Inbound Capital Intensive Processing",
  "Inbound Repair and Services",
  "Insurance",
  "Legal Services",
  "Non-Durable Merchandise Retail",
  "Outbound Consumer Service",
  "Petrochemical Extraction and Distribution",
  "Service Retail",
  "SIG Affiliations",
  "Social Services",
  "Special Outbound Trade Contractors",
  "Specialty Realty",
  "Transportation",
  "Utility Creation and Distribution",
  "Vehicle Retail",
  "Wholesale",
  "Shipping",
  "Consulting",
  "FinanceCar",
  "Marine Services",
  "Construction Industry",
  "Advertising",
  "Aerospace ",
  "Agriculture",
  "Aircraft",
  "Airline",
  "Apparel ",
  "Automotive",
  "Banking",
  "Biotechnology",
  "Broadcasting",
  "Brokerage",
  "Call Centers",
  "Cargo Handling ",
  "Chemical",
  "Computer",
  "Consumer Products",
  "Cosmetics",
  "Defense",
  "Department Stores",
  "Education",
  "Electronics",
  "Energy",
  "Entertainment ",
  "Executive Search",
  "Financial Services",
  "Food, Beverage ",
  "Grocery",
  "Health Care",
  "Internet Publishing",
  "Investment Banking",
  "Legal",
  "Manufacturing",
  "Motion Picture ",
  "Music",
  "Newspaper Publishers",
  "Online Auctions",
  "Pension Funds",
  "Pharmaceuticals",
  "Private Equity",
  "Publishing",
  "Real Estate",
  "Retail ",
  "Securities  Exchanges",
  "Service",
  "Soap ",
  "Software",
  "Sports",
  "Technology",
  "Telecommunications",
  "Television",
  "Trucking",
  "Venture Capital",
  "FOOD",
  "MECHANICAL",
  "PAPER",
  "MINERALS",
  "CONSTRUCTION",
  "GOODS PRODUCTION",
  "SUPPLY",
  "TRANSPORT & WASTE MANAGEMENT",
  "NUCLEAR",
  "HEALTH",
  "Agriculture null ",
  "Mining and Quarrying",
  "Food products, beverages and tobacco",
  "Textiles and textile products",
  "Leather  products",
  "Wood and wood products",
  "Pulp, paper, and paper products",
  "Publishing Companies",
  "Printing companies",
  "Manufacture of coke and refined petroleum products",
  "Nuclear fuel",
  "Chemicals, chemical products and fibres",
  "Pharmaceuticals",
  "Rubber and plastic products",
  "Non-metallic mineral products",
  "Concrete, cement, lime, plaster etc.",
  "Basic metals and fabricated metal products",
  "Machinery and equipment",
  "Electrical equipment, Optical and precision equipments and Medical and surgical equipment",
  "Shipbuilding",
  "Aerospace",
  "Other transport equipment",
  "Manufacturing not elsewhere classified",
  "Recycling",
  "Electricity supply",
  "Gas supply",
  "Water supply",
  "Construction",
  "Wholesale  trade; Repair of motor vehicles, motorcycles and Personal and household goods",
  "Hotels and Restaurant",
  "Transport, storage and communication",
  "Financial intermediation; Real estate; renting",
  "Information technology",
  "Engineering services",
  "Other services",
  "Public Administration",
  "Education",
  "Health and social work",
  "Other social services",
];

export const seedAuditorIdustory = async () => {
  for (const auditorIndustory of auditorIndustries) {
    await AuditorIndustry.findOrCreate({
      where: { name: auditorIndustory },
    });
  }
};
