import NaceCodeRev1 from "../../models/auditor/auditorNaceCodeRev1.js";

const naceCodeRevs1 = [
  "A 01.11 Growing of cereals and other crops n.e.c.",
  "A 01.12 Growing of vegetables, horticultural specialities and nursery products",
  "A 01.13 Growing of fruit, nuts, beverage and spice crops",
  "A 01.21 Farming of cattle, dairy farming",
  "A 01.22 Farming of sheep, goats, horses, asses, mules and hinnies",
  "A 01.13 Farming of swine",
  "A 01.24 Farming of poultry",
  "A 01.25 Other farming of animals",
  "A 01.30 Growing of crops combined with farming of animals (mixed farming)",
  "A 01.41 Agricultural service activities; landscape gardening",
  "A 01.42 Animal husbandry service activities, except veterinary activities",
  "A 01.50 Hunting, trapping and game propagation, including related service activities",
  "A 02.01 Forestry and logging",
  "A 02.02 Forestry and logging related service activities",
  "B 05.01 Fishing",
  "B 05.02 Fish farming",
  "CA 10.10 Mining and agglomeration of hard coal",
  "CA 10.20 Mining and agglomeration of lignite",
  "CA 10.30 Extraction and agglomeration of peat",
  "CA 11.10 Extraction of crude petroleum and natural gas",
  "CA 11.20 Service activities incidental to oil and gas extraction, excluding surveying",
  "CA 12.00 Mining of uranium and thorium ores",
  "CB 13.10 Mining of iron ores",
  "CB 13.20 Mining of non-ferrous metal ores, except uranium and thorium ores",
  "CB 14.11 Quarrying of  ornamental and building stone",
  "CB 14.12 Quarrying of limestone, gypsum and chalk",
  "CB 14.13 Quarrying of slate",
  "CB 14.21 Operation of gravel and sand pits",
  "CB 14.22 Mining of clays and kaolin",
  "CB 14.30 Mining of chemical and fertilizer minerals",
  "CB 14.40 Production of salt",
  "CB 14.50 Other mining and quarrying n.e.c.",
  "DA 15.11 Production and preserving of meat",
  "DA 15.12 Production and preserving of poultrymeat",
  "DA 15.13 Production of meat and poultrymeat products",
  "DA 15.20 Processing and preserving of fish and fish products",
  "DA 15.31 Processing and preserving of potatoes",
  "DA 15.32 Manufacture of fruit and vegetable juice",
  "DA 15.33 Processing and preserving of fruit and vegetables n.e.c.",
  "DA 15.41 Manufacture of crude oils and fats",
  "DA 15.42 Manufacture of refined oils and fats",
  "DA 15.43 Manufacture of margarine and similar edible fats",
  "DA DA 15.51 Operation of dairies and cheese making",
  "DA 15.52 Manufacture of ice cream",
  "DA 15.61 Manufacture of grain mill products",
  "DA 15.62 Manufacture of starches and starch products",
  "DA 15.71 Manufacture of prepared feeds for farm animals",
  "DA 15.72 Manufacture of prepared pet foods",
  "DA 15.81 Manufacture of bread; manufacture of fresh pastry goods and cakes",
  "DA 15.82 Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes",
  "DA 15.83 Manufacture of sugar",
  "DA 15.84 Manufacture of cocoa; chocolate and sugar confectionery",
  "DA 15.85 Manufacture of macaroni, noodles, couscous and similar farinaceous products",
  "DA 15.86 Processing of tea and coffee",
  "DA 15.87 Manufacture of condiments and seasonings",
  "DA 15.88 Manufacture of homogenised food preparations and dietetic food",
  "DA 15.89 Manufacture of other food products n.e.c.",
  "DA 15.91 Manufacture of distilled potable alcoholic beverages",
  "DA 15.92 Production of ethyl alcohol from fermented materials",
  "DA 15.93 Manufacture of wines",
  "DA 15.94 Manufacture of cider and other fruit wines",
  "DA 15.95 Manufacture of other non-distilled fermented beverages",
  "DA 15.96 Manufacture of beer",
  "DA 15.97 Manufacture of malt",
  "DA 15.98 Production of mineral waters and soft drinks",
  "DA 16.00 Manufacture of tobacco products",
  "DB 17.11 Preparation and spinning of cotton-type fibres",
  "DB 17.12 Preparation and spinning of woollen-type fibres",
  "DB 17.13 Preparation and spinning of worsted-type fibres",
  "DB 17.14 Preparation and spinning of flax-type fibres",
  "DB 17.15 Throwing and preparation of silk, including from noils; and throwing and texturing of synthetic or artificial",
  "DB 17.16 Manufacture of sewing threads",
  "DB 17.17	Preparation and spinning of other textile fibres",
  "DB 17.21	Cotton-type weaving",
  "DB 17.22	Woollen-type weaving",
  "DB 17.23	Worsted-type weaving",
  "DB 17.24	Silk-type weaving",
  "DB 17.25	Other textile weaving",
  "DB 17.30	Finishing of textiles",
  "DB 17.40	Manufacture of made-up textile articles, except apparel",
  "DB 17.51	Manufacture of carpets and rugs",
  "DB 17.52	Manufacture of cordage, rope, twine and netting",
  "DB 17.53 Manufacture of non-wovens and articles made from non-wovens, except apparel",
  "DB 17.54 Manufacture of other textiles n.e.c.",
  "DB 17.60 Manufacture of knitted and crocheted fabrics",
  "DB 17.71 Manufacture of knitted and crocheted hosiery",
  "DB 17.72 Manufacture of knitted and crocheted pullovers, cardigans and similar articles",
  "DB 18.10 Manufacture of leather clothes",
  "DB 18.21 Manufacture of workwear",
  "DB 18.22 Manufacture of other outerwear",
  "DB 18.23 Manufacture of underwear",
  "DB 18.24 Manufacture of other wearing apparel and accessories n.e.c.",
  "DB 18.30 Dressing and dyeing of fur; manufacture of articles of fur",
  "DB 19.10 Tanning and dressing of leather",
  "DC 19.20 Manufacture of luggage, handbags and the like, saddlery and harness",
  "DC 19.30 Manufacture of footwear",
  "DD 20.10 Sawmilling and planing of wood; impregnation of wood",
  "DD 20.20 Manufacture of veneer sheets; manufacture of plywood, laminboard, particle board, fibre board and other panels and boards",
  "DD 20.30 Manufacture of builders' carpentry and joinery",
  "DD 20.40 Manufacture of wooden containers",
  "DD 20.51 Manufacture of other products of wood",
  "DD 20.52 Manufacture of articles of cork, straw and plaiting materials",
  "DE 21.11 Manufacture of pulp",
  "DE 21.12 Manufacture of paper and paperboard",
  "DE 21.21 Manufacture of corrugated paper and paperboard and of containers of paper and paperboard",
  "DE 21.22 Manufacture of household and sanitary goods and of toilet requisites",
  "DE 21.23 Manufacture of paper stationery",
  "DE 21.24 Manufacture of wallpaper",
  "DE 21.25 Manufacture of other articles of paper and paperboard n.e.c.",
  "DE 22.11 Publishing of books",
  "DE 22.12 Publishing of newspapers",
  "DE 22.13 Publishing of journals and periodicals",
  "DE 22.14 Publishing of sound recordings",
  "DE 22.15 Other publishing",
  "DE 22.21 Printing of newspapers",
  "DE 22.22 Printing n.e.c.",
  "DE 22.23 Bookbinding",
  "DE 22.24 Pre-press activities",
  "DE 22.25 Ancillary activities related to printing",
  "DE 22.31 Reproduction of sound recording",
  "DE 22.32 Reproduction of video recording",
  "DE 22.33 Reproduction of computer media",
  "DF 23.10 Manufacture of coke oven products",
  "DF 23.20 Manufacture of refined petroleum products",
  "DF 23.30 Processing of nuclear fuel",
  "DG 24.11 Manufacture of industrial gases",
  "DG 24.12 Manufacture of dyes and pigments",
  "DG 24.13 Manufacture of other inorganic basic chemicals",
  "DG 24.14 Manufacture of other organic basic chemicals",
  "DG 24.15 Manufacture of fertilizers and nitrogen compounds",
  "DG 24.16 Manufacture of plastics in primary forms",
  "DG 24.17 Manufacture of synthetic rubber in primary forms",
  "DG 24.20 Manufacture of pesticides and other agro-chemical products",
  "DG 24.30 Manufacture of paints, varnishes and similar coatings, printing ink and mastics",
  "DG 24.41 Manufacture of basic pharmaceutical products",
  "DG 24.42 Manufacture of pharmaceutical preparations",
  "DG 24.51 Manufacture of soap and detergents, cleaning and polishing preparations",
  "DG 24.52 Manufacture of perfumes and toilet preparations",
  "DG 24.61 Manufacture of explosives",
  "DG 24.62 Manufacture of glues and gelatines",
  "DG 24.63 Manufacture of essential oils",
  "DG 24.64 Manufacture of photographic chemical material",
  "DG 24.65 Manufacture of prepared unrecorded media",
  "DG 24.66 Manufacture of other chemical products n.e.c",
  "DG 24.70 Manufacture of man-made fibres",
  "DH 25.11 Manufacture of rubber tyres and tubes",
  "DH 25.12 Retreading and rebuilding of rubber tyres",
  "DH 25.13 Manufacture of other rubber products",
  "DH 25.21 Manufacture of plastic plates, sheets, tubes and profiles",
  "DH 25.22 Manufacture of plastic packing goods",
  "DH 25.23 Manufacture of builders' ware of plastic",
  "DH 25.24 Manufacture of other plastic products",
  "DI 26.11 Manufacture of flat glass",
  "DI 26.12 Shaping and processing of flat glass",
  "DI 26.13 Manufacture of hollow glass",
  "DI 26.14 Manufacture of glass fibres",
  "DI 26.15 Manufacture and processing of other glass, including technical glassware",
  "DI 26.21 Manufacture of ceramic household and ornamental articles",
  "DI 26.22 Manufacture of ceramic sanitary fixtures",
  "DI 26.23 Manufacture of ceramic insulators and insulating fittings",
  "DI 26.24 Manufacture of other technical ceramic products",
  "DI 26.25 Manufacture of other ceramic products",
  "DI 26.26 Manufacture of refractory ceramic products",
  "DI 26.30 Manufacture of ceramic tiles and flags",
  "DI 26.40 Manufacture of bricks, tiles and construction products, in baked clay",
  "DI 26.51 Manufacture of cement",
  "DI 26.52 Manufacture of lime",
  "DI 26.53 Manufacture of plaster",
  "DI 26.61 Manufacture of concrete products for construction purposes",
  "DI 26.62 Manufacture of plaster products for construction purposes",
  "DI 26.63 Manufacture of ready-mixed concrete",
  "DI 26.64 Manufacture of mortars",
  "DI 26.65 Manufacture of fibre cement",
  "DI 26.66 Manufacture of other articles of concrete, plaster and cement",
  "DI 26.70 Cutting, shaping and finishing of ornamental and building stone",
  "DI 26.81 Production of abrasive products",
  "DI 26.82 Manufacture of other non-metallic mineral products n.e.c.",
  "DJ 27.10 Manufacture of basic iron and steel and of ferro-alloys",
  "DJ 27.21 Manufacture of cast iron tubes",
  "DJ 27.22 Manufacture of steel tubes",
  "DJ 27.31 Cold drawing",
  "DJ 27.32 Cold rolling of narrow strip",
  "DJ 27.33 Cold forming or folding",
  "DJ 27.34 Wire drawing",
  "DJ 27.41 Precious metals production",
  "DJ 27.42 Aluminium production",
  "DJ 27.43 Lead, zinc and tin production",
  "DJ 27.44 Copper production",
  "DJ 27.45 Other non-ferrous metal production",
  "DJ 27.51 Casting of iron",
  "DJ 27.52 Casting of steel",
  "DJ 27.53 Casting of light metals",
  "DJ 27.54 Casting of other non-ferrous metals",
  "DJ 28.00 Manufacture of fabricated metal products, except machinery and equipment",
  "DJ 28.11 Manufacture of metal structures and parts of structures",
  "DJ 28.12 Manufacture of builders' carpentry and joinery of metal",
  "DJ 28.21 Manufacture of tanks, reservoirs and containers of metal",
  "DJ 28.22 Manufacture of central heating radiators and boilers",
  "DJ 28.30 Manufacture of steam generators, except central heating hot water boilers",
  "DJ 28.40 Forging, pressing, stamping and roll forming of metal; powder metallurgy",
  "DJ 28.51 Treatment and coating of metals",
  "DJ 28.52 General mechanical engineering",
  "DJ 28.61 Manufacture of cutlery",
  "DJ 28.62 Manufacture of tools",
  "DJ 28.63 Manufacture of locks and hinges",
  "DJ 28.71 Manufacture of steel drums and similar containers",
  "DJ 28.72 Manufacture of light metal packaging",
  "DJ 28.73 Manufacture of wire products",
  "DJ 28.74 Manufacture of fasteners, screw machine products, chain and springs",
  "DJ 28.75 Manufacture of other fabricated metal products n.e.c.",
  "DK 29.00 Manufacture of machinery and equipment n.e.c.",
  "DK 29.11 Manufacture of engines and turbines, except aircraft, vehicle and cycle engines",
  "DK 29.12 Manufacture of pumps and compressors",
  "DK 29.13 Manufacture of taps and valves",
  "DK 29.14 Manufacture of bearings, gears, gearing and driving elements",
  "DK 29.21 Manufacture of furnaces and furnace burners",
  "DK 29.22 Manufacture of lifting and handling equipment",
  "DK 29.23 Manufacture of non-domestic cooling and ventilation equipment",
  "DK 29.24 Manufacture of other general purpose machinery n.e.c.",
  "DK 29.31 Manufacture of agricultural tractors",
  "DK 29.32 Manufacture of other agricultural and forestry machinery",
  "DK 29.41 Manufacture of portable hand held power tools",
  "DK 29.42 Manufacture of other metalworking machine tools",
  "DK 29.43 Manufacture of other machine tools n.e.c.",
  "DK 29.51 Manufacture of machinery for metallurgy",
  "DK 29.52 Manufacture of machinery for mining, quarrying and construction",
  "DK 29.53 Manufacture of machinery for food, beverage and tobacco processing",
  "DK 29.54 Manufacture of machinery for textile, apparel and leather production",
  "DK 29.55 Manufacture of machinery for paper and paperboard production",
  "DK 29.56 Manufacture of other special purpose machinery n.e.c.",
  "DK 29.60 Manufacture of weapons and ammunition",
  "DK 29.71 Manufacture of electric domestic appliances",
  "DK 29.72 Manufacture of non-electric domestic appliances",
  "DL 30.00 Manufacture of office machinery and computers",
  "DL 30.01 Manufacture of office machinery",
  "DL 30.02 Manufacture of computers and other information processing equipment",
  "DL 31.00 Manufacture of electrical machinery and apparatus n.e.c.",
  "DL 31.10 Manufacture of electric motors, generators and transformers",
  "DL 31.20 Manufacture of electricity distribution and control apparatus",
  "DL 31.30 Manufacture of insulated wire and cable",
  "DL 31.40 Manufacture of accumulators, primary cells and primary batteries",
  "DL 31.50 Manufacture of lighting equipment and electric lamps",
  "DL 31.61 Manufacture of electrical equipment for engines and vehicles n.e.c.",
  "DL 31.62 Manufacture of other electrical equipment n.e.c.",
  "DL 32.00 Manufacture of radio, television and communication equipment and apparatus",
  "DL 32.10 Manufacture of electronic valves and tubes and other electronic components",
  "DL 32.20 Manufacture of television and radio transmitters and apparatus for line telephony and line telegraphy",
  "DL 32.30 Manufacture of television and radio receivers, sound or video recording or reproducing apparatus and associated goods",
  "DL 33.00 Manufacture of medical, precision and optical instruments, watches and clocks",
  "DL 33.10 Manufacture of medical and surgical equipment and orthopaedic appliances",
  "DL 33.20 Manufacture of instruments and appliances for measuring, checking, testing, navigating and other purposes, except industrial process control equipment",
  "DL 33.30 Manufacture of industrial process control equipment",
  "DL 33.40 Manufacture of optical instruments and photographic equipment",
  "DL 33.50 Manufacture of watches and clocks",
  "DM 34.00 Manufacture of motor vehicles, trailers and semi-trailers",
  "DM 34.10 Manufacture of motor vehicles",
  "DM 34.20 Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers",
  "DM 34.30 Manufacture of parts and accessories for motor vehicles and their engines",
  "DM 35.00 Manufacture of other transport equipment",
  "DM 35.11 Building and repairing of ships",
  "DM 35.12 Building and repairing of pleasure and sporting boats",
  "DM 35.20 Manufacture of railway and tramway locomotives and rolling stock",
  "DM 35.30 Manufacture of aircraft and spacecraft",
  "DM 35.41 Manufacture of motorcycles",
  "DM 35.42 Manufacture of bicycles",
  "DM 35.43 Manufacture of invalid carriages",
  "DM 35.50 Manufacture of other transport equipment n.e.c.",
  "DN 36.00 Manufacture of furniture; manufacturing n.e.c.",
  "DN 36.11 Manufacture of chairs and seats",
  "DN 36.12 Manufacture of other office and shop furniture",
  "DN 36.13 Manufacture of other kitchen furniture",
  "DN 36.14 Manufacture of other furniture",
  "DN 36.15 Manufacture of mattresses",
  "DN 36.21 Striking of coins",
  "DN 36.22 Manufacture of jewellery and related articles n.e.c.",
  "DN 36.30 Manufacture of musical instruments",
  "DN 36.40 Manufacture of sports goods",
  "DN 36.50 Manufacture of games and toys",
  "DN 36.61 Manufacture of imitation jewellery",
  "DN 36.62 Manufacture of brooms and brushes",
  "DN 36.63 Other manufacturing n.e.c.",
  "DN 37.10 Recycling of metal waste and scrap",
  "DN 37.20 Recycling of non-metal waste and scrap",
  "E 40.11 Production of electricity",
  "E 40.12 Transmission of electricity",
  "E 40.13 Distribution and trade of electricity",
  "E 40.21 Manufacture of gas",
  "E 40.22 Distribution and trade of gaseous fuels through mains",
  "E 40.30 Steam and hot water supply",
  "E 41.00 Collection, purification and distribution of water",
  "E 45.11 Demolition and wrecking of buildings; earth moving",
  "F 45.12 Test drilling and boring",
  "F 45.21 General construction of buildings and civil engineering works",
  "F 45.22 Erection of roof covering and frames",
  "F 45.23 Construction of motorways, roads, airfields and sport facilities",
  "F 45.24 Construction of water projects",
  "F 45.25 Other construction work involving special trades",
  "F 45.31 Installation of electrical wiring and fittings",
  "F 45.32 Insulation work activities",
  "F 45.33 Plumbing",
  "F 45.34 Other building installation",
  "F 45.41 Plastering",
  "F 45.42 Joinery installation",
  "F 45.43 Floor and wall covering",
  "F 45.44 Painting and glazing",
  "F 45.45 Other building completion",
  "F 45.50 Renting of construction or demolition equipment with operator",
  "G 50.10 Sale of motor vehicles",
  "G 50.20 Maintenance and repair of motor vehicles",
  "G 50.30 Sale of motor vehicle parts and accessories",
  "G 50.40 Sale, maintenance and repair of motorcycles and related parts and accessories",
  "G 50.50 Retail sale of automotive fuel",
  "G 51.11 Agents involved in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods",
  "G 51.12 Agents involved in the sale of fuels, ores, metals and industrial chemicals",
  "G 51.13 Agents involved in the sale of timber and building materials",
  "G 51.14 Agents involved in the sale of machinery, industrial equipment, ships and aircraft",
  "G 51.15 Agents involved in the sale of furniture, household goods, hardware and ironmongery",
  "G 51.16 Agents involved in the sale of textiles, clothing, footwear and leather goods",
  "G 51.17 Agents involved in the sale of food, beverages and tobacco",
  "G 51.18 Agents specialising in the sale of particular products or ranges of products n.e.c.",
  "G 51.19 Agents involved in the sale of a variety of goods",
  "G 51.21 Wholesale of grain, seeds and animal feeds",
  "G 51.22 Wholesale of flowers and plants",
  "G 51.23 Wholesale of live animals",
  "G 51.24 Wholesale of hides, skins and leather",
  "G 51.25 Wholesale of unmanufactured tobacco",
  "G 51.31 Wholesale of fruit and vegetables",
  "G 51.32 Wholesale of meat and meat products",
  "G 51.33 Wholesale of dairy produce, eggs and edible oils and fats",
  "G 51.34 Wholesale of alcoholic and other beverages",
  "G 51.35 Wholesale of tobacco products",
  "G 51.36 Wholesale of sugar and chocolate and sugar confectionery",
  "G 51.37 Wholesale of coffee, tea, cocoa and spices",
  "G 51.38 Wholesale of other food, including fish, crustaceans and molluscs",
  "G 51.39 Non-specialised wholesale of food, beverages and tobacco",
  "G 51.41 Wholesale of textiles",
  "G 51.42 Wholesale of clothing and footwear",
  "G 51.43 Wholesale of electrical household appliances and radio and television goods",
  "G 51.44 Wholesale of china and glassware, wallpaper and cleaning materials",
  "G 51.45 Wholesale of perfume and cosmetics",
  "G 51.46 Wholesale of pharmaceutical goods",
  "G 51.47 Wholesale of other household goods",
  "G 51.51 Wholesale of solid, liquid and gaseous fuels and related products",
  "G 51.52 Wholesale of metals and metal ores",
  "G 51.53 Wholesale of wood, construction materials and sanitary equipment",
  "G 51.54 Wholesale of hardware, plumbing and heating equipment and supplies",
  "G 51.55 Wholesale of chemical products",
  "G 51.56 Wholesale of other intermediate products",
  "G 51.57 Wholesale of waste and scrap",
  "G 51.81 Wholesale of machine tools",
  "G 51.82 Wholesale of mining, construction and civil engineering machinery",
  "G 51.83 Wholesale of machinery for the textile industry and of sewing and knitting machines",
  "G 51.84 Wholesale of computers, computer peripheral equipment and software",
  "G 51.85 Wholesale of other office machinery and equipment",
  "G 51.86 Wholesale of other electronic parts and equipment",
  "G 51.87 Wholesale of other machinery for use in industry, trade and navigation",
  "G 51.88 Wholesale of agricultural machinery and accessories and implements, including tractors",
  "G 51.90 Other wholesale",
  "G 52.11 Retail sale in non-specialised stores with food, beverages or tobacco predominating",
  "G 52.12 Other retail sale in non-specialised stores",
  "G 52.21 Retail sale of fruit and vegetables",
  "G 52.22 Retail sale of meat and meat products",
  "G 52.23 Retail sale of fish, crustaceans and molluscs",
  "G 52.24 Retail sale of bread, cakes, flour confectionery and sugar confectionery",
  "G 52.25 Retail sale of alcoholic and other beverages",
  "G 52.26 Retail sale of tobacco products",
  "G 52.27 Other retail sale of food, beverages and tobacco in specialised stores",
  "G 52.31 Dispensing chemists",
  "G 52.32 Retail sale of medical and orthopaedic goods",
  "G 52.33 Retail sale of cosmetic and toilet articles",
  "G 52.41 Retail sale of textiles",
  "G 52.42 Retail sale of clothing",
  "G 52.43 Retail sale of footwear and leather goods",
  "G 52.44 Retail sale of furniture, lighting equipment and household articles n.e.c.",
  "G 52.45 Retail sale of electrical household appliances and radio and television goods",
  "G 52.46 Retail sale of hardware, paints and glass",
  "G 52.47 Retail sale of books, newspapers and stationery",
  "G 52.48 Other retail sale in specialised stores",
  "G 52.49 Retail sale via stalls and markets",
  "G 52.50 Retail trade not in stores",
  "G 52.61 Retail sale via mail order houses",
  "G 52.62 Retail sale via internet",
  "G 52.63 Retail sale via stalls and markets",
  "G 52.7 Repair of personal and household goods",
  "G 52.71 Repair of boots, shoes and other articles of leather",
  "G 52.72 Repair of electrical household goods",
  "G 52.73 Repair of watches, clocks and jewellery",
  "G 52.74 Repair n.e.c.",
  "H 53.10 Transport and storage",
  "H 53.20 Postal services",
  "H 55.10 Hotels",
  "H 55.21 Youth hostels and mountain refuges",
  "H 55.22 Camping sites, including caravan sites",
  "H 55.23 Other provision of lodgings n.e.c.",
  "H 55.30 Restaurants",
  "H 55.40 Bars",
  "H 55.51 Canteens",
  "H 55.52 Catering",
  "I 60.10 Transport via railways",
  "I 60.21 Other scheduled passenger land transport",
  "I 60.22 Taxi operation",
  "I 60.23 Other land passenger transport",
  "I 60.24 Freight transport by road",
  "I 60.30 Transport via pipelines",
  "I 61.10 Sea and coastal water transport",
  "I 61.20 Inland water transport",
  "I 62.10 Scheduled air transport",
  "I 62.20 Non-scheduled air transport",
  "I 62.30 Space transport",
  "I 63.11 Cargo handling",
  "I 63.12 Storage and warehousing",
  "I 63.21 Other supporting land transport activities",
  "I 63.22 Other supporting water transport activities",
  "I 63.23 Other supporting air transport activities",
  "I 63.30 Activities of travel agencies and tour operators; tourist assistance activities n.e.c.",
  "I 63.40 Activities of other transport agencies",
  "I 64.11 National post activities",
  "I 64.12 Courier activities other than national post activities",
  "I 64.20 Telecommunications",
  "J 65.11 Central banking",
  "J 65.12 Other monetary intermediation",
  "J 65.21 Financial leasing",
  "J 65.22 Other credit granting",
  "J 65.23 Other financial intermediation n.e.c.",
  "J 66.01 Life insurance",
  "J 66.02 Pension funding",
  "J 66.03 Non-life insurance",
  "J 67.11 Administration of financial markets",
  "J 67.12 Security broking and fund management",
  "J 67.13 Activities auxiliary to financial intermediation n.e.c.",
  "J 67.20 Activities auxiliary to insurance and pension funding",
  "K 70.11 Development and selling of real estate",
  "K 70.12 Buying and selling of own real estate",
  "K 70.20 Letting of own property",
  "K 70.31 Real estate agencies",
  "K 70.32 Management of real estate on a fee or contract basis",
  "K 71.10 Renting of automobiles",
  "K 71.21 Renting of other land transport equipment",
  "K 71.22 Renting of water transport equipment",
  "K 71.23 Renting of air transport equipment",
  "K 71.31 Renting of agricultural machinery and equipment",
  "K 71.32 Renting of construction and civil engineering machinery and equipment",
  "K 71.33 Renting of office machinery and equipment, including computers",
  "K 71.34 Renting of other machinery and equipment n.e.c.",
  "K 71.40 Renting of personal and household goods n.e.c.",
  "K 72.10 Hardware consultancy",
  "K 72.21 Publishing of software",
  "K 72.22 Other software consultancy and supply",
  "K 72.30 Data processing",
  "K 72.40 Database activities",
  "K 72.50 Maintenance and repair of office, accounting and computing machinery",
  "K 72.60 Other computer related activities",
  "K 73.10 Research and experimental development on natural sciences and engineering",
  "K 73.20 Research and experimental development on social sciences and humanities",
  "K 74.11 Legal activities",
  "K 74.12 Accounting, book-keeping and auditing activities; tax consultancy",
  "K 74.13 Market research and public opinion polling",
  "K 74.14 Business and management consultancy activities",
  "K 74.15 Management activities of holding companies",
  "K 74.20 Architectural and engineering activities and related technical consultancy",
  "K 74.30 Technical testing and analysis",
  "K 74.40 Advertising",
  "K 74.50 Labour recruitment and provision of personnel",
  "K 74.60 Investigation and security activities",
  "K 74.70 Industrial cleaning",
  "K 74.81 74.5",
  "K 74.82 Packaging activities",
  "K 74.85 Secretarial and translation activities",
  "K 74.86 Call centre activities",
  "K 74.87 Other business activities n.e.c.",
  "L 75.11 General (overall) public service activities",
  "L 75.12 Regulation of the activities of agencies that provide health care, education, cultural services and other social services, excluding social security",
  "L 75.13 Regulation of and contribution to more efficient operation of business",
  "L 75.14 Supporting service activities for the government as a whole",
  "L 75.21 Foreign affairs",
  "L 75.22 Defence activities",
  "L 75.23 Justice and judicial activities",
  "L 75.24 Public security, law and order activities",
  "L 75.25 Fire service activities",
  "L 75.30 Compulsory social security activities",
  "M 80.10 Primary education",
  "M 80.21 General secondary education",
  "M 80.22 Technical and vocational secondary education",
  "M 80.30 Higher education",
  "M 80.41 Driving school activities",
  "M 80.42 Adult and other education n.e.c.",
  "N 85.11 Hospital activities",
  "N 85.12 Medical practice activities",
  "N 85.13 Dental practice activities",
  "N 85.14 Other human health activities",
  "N 85.20 Veterinary activities",
  "N 85.31 Social work activities with accommodation",
  "N 85.32 Social work activities without accommodation",
  "O 90.01 Collection and treatment of sewage",
  "O 90.02 Collection and treatment of other waste",
  "O 90.03 Sanitation, remediation and similar activities",
  "O 91.11 Activities of business and employers' organizations",
  "O 91.12 Activities of professional organizations",
  "O 91.20 Activities of trade unions",
  "O 91.31 Activities of religious organizations",
  "O 91.32 Activities of political organizations",
  "O 91.33 Activities of other membership organizations n.e.c.",
  "O 92.11 Motion picture and video production",
  "O 92.12 Motion picture and video distribution",
  "O 92.13 Motion picture projection",
  "O 92.20 Radio and television activities",
  "O 92.31 Artistic and literary creation and interpretation",
  "O 92.32 Operation of arts facilities",
  "O 92.33 Fair and amusement park activities",
  "O 92.34 Other entertainment activities n.e.c.",
  "O 92.40 News agency activities",
  "O 92.51 Library and archives activities",
  "O 92.52 Museums activities and preservation of historical sites and buildings",
  "O 92.53 Botanical and zoological gardens and nature reserves activities",
  "O 92.61 Operation of sports arenas and stadiums",
  "O 92.62 Other sporting activities",
  "O 92.71 Gambling and betting activities",
  "O 92.72 Other recreational activities n.e.c.",
  "O 93.01 Washing and dry-cleaning of textile and fur products",
  "O 93.02 Hairdressing and other beauty treatment",
  "O 93.03 Funeral and related activities",
  "O 93.04 Physical well-being activities",
  "O 93.05 Other service activities n.e.c.",
  "P 95.00 Activities of households as employers of domestic staff",
  "P 96.00 Undifferentiated goods producing activities of private households for own use",
  "P 97.00 Undifferentiated services producing activities of private households for own use",
  "Q 99.00 Extra-territorial organizations and bodies"
];

export const seedNaceCodeRev1 = async () => {
  for (const naceCodeRev1 of naceCodeRevs1) {
    await NaceCodeRev1.findOrCreate({
      where: { name: naceCodeRev1 },
    });
  }
};
